apiVersion: v1
kind: Service
metadata:
  name: ftps-svc
  annotations: 
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: ftps
  type: LoadBalancer
  loadBalancerIP: 192.168.99.104
  ports:
    - protocol: TCP
      name: fisrt
      port: 20
      targetPort: 20
    - protocol: TCP
      name: second
      port: 21
      targetPort: 21
    - protocol: TCP
      name: third
      port: 52025
      targetPort: 52025
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps_image
        imagePullPolicy: Never
        ports:
        - containerPort: 20
        - containerPort: 21
        - containerPort: 52025
        livenessProbe:
          exec:
            command:
            - pgrep
            - /usr/sbin/vsftpd
          initialDelaySeconds: 10
          periodSeconds: 5