apiVersion: v1
kind: Service
metadata:
  name: influxdb-svc
  annotations: 
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: influxdb
  type: LoadBalancer
  loadBalancerIP: 192.168.99.104
  ports:
    - protocol: TCP
      name: influxdb
      port: 8086
      targetPort: 8086
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb-deployment
  labels:
    app: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
      - name: influxdb
        image: influxdb_image
        imagePullPolicy: Never
        ports:
        - containerPort: 8086
          name: influxdb
        volumeMounts:
          - mountPath: "/var/lib/influxdb"
            name: influxdb-pv-volume
          - name: influxdb
            mountPath: /etc/influxdb/influxdb.conf
            subPath: influxdb.conf
            readOnly: true
      volumes:
      - name: influxdb-pv-volume
        persistentVolumeClaim:
          claimName: influxdb-pv-claim
      - name: influxdb
        configMap:
          name: influxdb
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: influxdb-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/influxdb"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-pv-claim
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi